### ISSUE TITLE
bundleConfig

### ISSUE THREAD

**Issue by GeezerUK** [atribecalledkwest/nodecg-streamlabs#4]
where is the bundleConfig so i can add the token as in the 'configschema.json' i have added my token key 

but i am always getting this error - error: [nodecg-streamlabs] No socket_token value present in bundleConfig

here is my configschema.json 
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "socket_token": {
            "type": "string",
            "value": "[redacted]",
            "description": "The socket_token used to connect to StreamLabs"
        },
        "socketio": {
            "type": "object",
            "value": {

            },
            "description": "Optional values passed directly to the Socket.IO client"
        },
        "required": ["socket_token"]
    }
}

**Comment by atribecalledkwest** [comment]
Sorry for not responding, took a break from basically opening GitHub.

bundleConfig is located in the `cfg` folder in NodeCG. You need to make a file in the `cfg` folder with the name `nodecg-streamlabs.json`, then write the appropriate configuration file there.

The configschema.json is not an example config, it is meant to be a "schema" for nodecg when generating a default configuration file. If you're unsure, you can use the `nodecg-cli` package from NPM to generate a default config using `nodecg defaultconfig`.
